# Generated by Django 3.2.12 on 2022-03-31 14:48

from django.db import migrations, models
import main_app.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debtors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_order', models.IntegerField(default=0, verbose_name='№ платёжного поручения')),
                ('personal_account', models.CharField(default='', max_length=100, verbose_name='№ лицевого счёта')),
                ('last_paid_month', models.CharField(default='', max_length=100, verbose_name='Последний оплаченный месяц')),
            ],
            options={
                'verbose_name': 'Должник',
                'verbose_name_plural': 'Должники',
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Отображаемое имя документа')),
                ('document', models.FileField(upload_to='documents/', verbose_name='Имя файла')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='MainPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to=main_app.utils.rename_main_picture, verbose_name='Фото главного экрана')),
            ],
            options={
                'verbose_name': 'Изменяемый объект',
                'verbose_name_plural': 'Изменяемые объекты',
            },
        ),
        migrations.CreateModel(
            name='MeterReadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_number', models.CharField(max_length=60, verbose_name='№ участка')),
                ('personal_account', models.CharField(max_length=60, verbose_name='№ лицевого счета')),
                ('current_day', models.IntegerField(default=0, verbose_name='текущие показания день')),
                ('current_night', models.IntegerField(default=0, verbose_name='текущие показания ночь')),
            ],
            options={
                'verbose_name': 'Показания электро энергии',
                'verbose_name_plural': 'Показания электро энергии',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Заголовок')),
                ('text', models.CharField(max_length=3000, verbose_name='Текст новости')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-id'],
            },
        ),
    ]
