# Generated by Django 3.2.12 on 2022-03-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_number', models.CharField(max_length=60)),
                ('personal_account', models.CharField(max_length=60)),
                ('current_day', models.IntegerField(default=0)),
                ('current_night', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('text', models.CharField(max_length=3000)),
                ('picture', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
